name: Create Release

on:
  workflow_dispatch:
    inputs:
      commitSha:
        description: 'Commit SHA'     
        required: true
        default: ''
      package:
        description: 'Package (folder)'  
        required: true
        default: ''
      oldVersion:
        description: 'old version'  
        required: true
        default: '[no-version]'

jobs:
  createRelease:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commitSha }}

    - name: install
      run: |
        Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version
        $PSVersionTable
        git --version
        choco --version
        Get-ChildItem env:* | sort-object name
        git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
        Import-Module "$($Env:TEMP)/au/AU/AU.psm1"

    - name: do release
      run: |
        $ErrorActionPreference = 'Stop'
        cd "${{ github.event.inputs.package }}"
        choco pack

        $item = (Get-ChildItem -Filter *.nupkg) | select -First 1
        $version = $item.BaseName.Replace("${{ github.event.inputs.package }}.", "")
        $folder = $item.Directory.FullName

        $info = [pscustomobject]@{result=[pscustomobject]@{pushed=,@([pscustomobject]@{Name="${{ github.event.inputs.package }}";"NuspecVersion"= "${{ github.event.inputs.oldVersion }}";"RemoteVersion"= "$version";"Path"= "$folder";})}}

        Write-Host "Info:"
        ConvertTo-Json $info -Depth 50

        ."$($Env:TEMP)/au/AU/Plugins/GitReleases.ps1" -Info $info -ApiToken ${{ secrets.GH_API_KEY }} -releaseType package -Branch "${{ github.event.inputs.commitSha }}"